name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=subhransude/gitgrabber
          docker build -t ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest -t ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:${{ github.run_number }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:${{ github.run_number }}
